[package]
name = "helium-proto"
version = "0.1.0"
authors = ["Helium <info@helium.com>"]
edition = "2018"

[features]
default = []
services = ["tonic-build", "tonic"]
deserailizers = ["byteorder","base64", "bs58"]

[dependencies]
tonic = {version = "0.4", optional = true}
prost = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = {version = "0", optional = true}
bs58 = {version = "0", features=["check"], optional = true}
byteorder =  {version = "0", optional = true}

[build-dependencies]
tonic-build = {version = "0.4", optional = true}
prost-build = "0.7"